# Generated by Django 3.2.7 on 2021-10-25 12:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_content_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
